site_name: GCES Kdenlive Relatórios
site_url: https://caeslucio.github.io/GCES-Kdenlive-relatorios/
repo_url: https://github.com/caeslucio/GCES-Kdenlive-relatorios
theme:
  name: material
  logo: assets/kdenlive-logo.svg
  favicon: assets/kdenlive-logo.svg
  language: pt-BR
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_javascript:
  - assets/js/open_links_new_tab.js

markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: .
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: 
    - Início: index.md
    - Comece por Aqui:
      - Como abrir um MR: materiais/como-abrir-mr.md
      - Regras para MRs: materiais/regras-para-mr.md
    - Modelos:
      - Template do Diário de bordo: materiais/template-diario-bordo.md
      - Template do relatório: materiais/template-relatorio.md
  - Sprints:
    - Sprint 0: geral/Sprint0.md
  - Contribuições individuais:
    - Caetano Santos Lucio - 180144979: contribuicoes_individuais/CaetanoLucio-180144979/Sprint0.md
    - Lucas Mendonça Arruda - 231035464: contribuicoes_individuais/LucasArruda-231035464/Sprint0.md
    - Júlia dos Reis Teixeira Massuda - 231035150: contribuicoes_individuais/JuliaMassuda-231035150/sprint0.md
    - Gustavo Oki - 231034716: contribuicoes_individuais/GustavoOki-231034716/sprint0.md
    - Karolina Vieira Barbosa - 202045820: contribuicoes_individuais/KarolinaVieira-202045820/sprint0.md

plugins:
  - search
  - tags
